{% set name = "rlpython" %}
{% set version = "0.8.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rlpython-{{ version }}.tar.gz
  sha256: 07ea5ce6e84e4f64332ba3952ea73bedf17562c583611dc4cbf653e42435c788

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - rlpython
    - rlpython.commands
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fscherf/rlpython
  summary: GNU Readline based Python REPL without any external dependencies
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
