{% set name = "rlpython" %}
{% set version = "0.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rlpython-{{ version }}.tar.gz
  sha256: b9575fa7483dc9197768c7b19c74b3b38f391661eadbdb8d8a9760c0282cf65b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - rlpython
    - rlpython.commands
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fscherf/rlpython
  summary: GNU Readline based Python REPL without any external dependencies
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
